### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by omo22** [rstrouse/nodejs-poolController-veraPlugin#1]
01	10/31/20 7:37:23.309	LuaInterface::CallFunction_Startup-1 device 845 function pcpInitialize failed [string "--..."]:184: attempt to index global 'self' (a nil value) <0x77508520>
01	10/31/20 7:37:23.310	LuImplementation::StartLua running startup code for 845 I_PoolController.xml failed <0x77508520>

using nodejs poolController 6.1
uploaded all files into vera and setup nodejs controller file config,json ip-vera and device ID 845 with  D_PoolController.xml
the config window within vera would not save, I had to add nodejs  IP xxxxx:4200 through advanced option vera device setup
no luck sofar 
an idea?

**Comment by rstrouse** [comment]
@omo22 -- I'm sorry git didn't notify me you posted an error here.  Anyhow setting the IP in there may be the issue.  You should go back  to the Configure page and set the IP there.  Change the Keep Equipment Together checkbox then change it back.  A Save Changes button should then appear.  Press it so that the IP address will be registered with Vera correctly.
